import colors from './colors';
import {
  ITEMS_BAVERAGES,
  ITEMS_BURGERS,
  ITEMS_DESERTS,
  ITEMS_MEALS,
  ITEMS_SALADS,
  LIST_ITEMS,
  LIST_MENU,
  SWITCH_HERO_IMAGE,
} from './menus';

export {
  colors,
  ITEMS_BAVERAGES,
  LIST_MENU,
  ITEMS_BURGERS,
  ITEMS_DESERTS,
  ITEMS_MEALS,
  ITEMS_SALADS,
  LIST_ITEMS,
  SWITCH_HERO_IMAGE,
};
