import colors from './colors';
import {
  ITEMS_BAVERAGES,
  ITEMS_BURGERS,
  ITEMS_DESSERTS,
  ITEMS_MEALS,
  ITEMS_SALADS,
  LIST_ITEMS,
  LIST_MENU,
  SWITCH_HERO_IMAGE,
  LIST_BURGER_MEALS,
  SELECT_ORDERS_METHOD,
  LIST_WALLET,
  LIST_TRANSACTION,
} from './menus';

export {
  colors,
  ITEMS_BAVERAGES,
  LIST_MENU,
  ITEMS_BURGERS,
  ITEMS_DESSERTS,
  LIST_WALLET,
  LIST_BURGER_MEALS,
  ITEMS_MEALS,
  LIST_TRANSACTION,
  SELECT_ORDERS_METHOD,
  ITEMS_SALADS,
  LIST_ITEMS,
  SWITCH_HERO_IMAGE,
};
